### ISSUE TITLE
Configuration Utils

### ISSUE THREAD

**Issue by ppadial** [ppadial/dotnet#11]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

An easy to use configuration utilities that implements my "default" policy of configuration which is:

1. Run Parameters
2. Environment variables (with prefix, optional)
3. Configuration file

**Describe alternatives you've considered**

A configuration class that uses Microsoft configuration extensions for netcore

**Additional context**

**Comment by Tyrrrz** [comment]
You might want to check out [CliFx](https://github.com/Tyrrrz/CliFx) because it seems it's doing exactly what you're trying to achieve here.

**Comment by ppadial** [comment]
Hi, thanks for the link.

So what im trying to achieve here is a configuration manager class, which is basically the same as the Microsoft configuration manager.

Clifx looks like mcmaster library + the cli lib i have in this repo. Looks quite good, good job.
